CREATE  TABLE ALUMNO
(
    ID NUMBER PRIMARY KEY,
    DNI VARCHAR2(20),
    CODIGO VARCHAR2(20),
    NOMBRES VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    ESTADO  CHAR(1)
);

CREATE  TABLE CURSO
(
    ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(150),
    CREDITOS NUMBER
);

CREATE  TABLE SECCION
(
    ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(150),
    CURSO_ID NUMBER,
    VACANTES_DISPONIBLE NUMBER,
    VACANTES_USADAS NUMBER,
    ESTADO  CHAR(1)
);


CREATE TABLE MATRICULA
(
    ID NUMBER PRIMARY KEY,
    ALUMNO_ID NUMBER,
    CURSO_ID NUMBER,
    SECCION_ID NUMBER,
    TIPO_MATRICULA CHAR(1),
    FECHA_REGISTRO DATE,
    FECHA_ANULACION DATE
);


 

INSERT INTO ALUMNO (ID,DNI,CODIGO,NOMBRES,APELLIDOS,ESTADO) VALUES (1,'70701001','00001','JOSE JAVIER','CAYCHO GARCIA','1');
INSERT INTO ALUMNO (ID,DNI,CODIGO,NOMBRES,APELLIDOS,ESTADO) VALUES (2,'70701002','00002','LUZMILA','SHICSHI','1');
INSERT INTO ALUMNO (ID,DNI,CODIGO,NOMBRES,APELLIDOS,ESTADO) VALUES (3,'70701003','00003','JOSSELYN','DOMINGUEZ','1');
INSERT INTO ALUMNO (ID,DNI,CODIGO,NOMBRES,APELLIDOS,ESTADO) VALUES (4,'70701004','00004','CARLOS','CAYCHO','1');
INSERT INTO ALUMNO (ID,DNI,CODIGO,NOMBRES,APELLIDOS,ESTADO) VALUES (5,'70701005','00005','VICTORIA','GARCIA','1');

INSERT INTO CURSO (ID,DESCRIPCION,CREDITOS) VALUES (1,'CURSO 1',2);
INSERT INTO CURSO (ID,DESCRIPCION,CREDITOS) VALUES (2,'CURSO 2',2);
INSERT INTO CURSO (ID,DESCRIPCION,CREDITOS) VALUES (3,'CURSO 3',3);
INSERT INTO CURSO (ID,DESCRIPCION,CREDITOS) VALUES (4,'CURSO 4',5);
INSERT INTO CURSO (ID,DESCRIPCION,CREDITOS) VALUES (5,'CURSO 5',6);

INSERT INTO SECCION (ID,DESCRIPCION,CURSO_ID,VACANTES_DISPONIBLE,VACANTES_USADAS,ESTADO) VALUES (1,'SECCION A',1,4,0,'1');
INSERT INTO SECCION (ID,DESCRIPCION,CURSO_ID,VACANTES_DISPONIBLE,VACANTES_USADAS,ESTADO) VALUES (2,'SECCION B',2,1,0,'1');
INSERT INTO SECCION (ID,DESCRIPCION,CURSO_ID,VACANTES_DISPONIBLE,VACANTES_USADAS,ESTADO) VALUES (3,'SECCION B',3,3,0,'1');
INSERT INTO SECCION (ID,DESCRIPCION,CURSO_ID,VACANTES_DISPONIBLE,VACANTES_USADAS,ESTADO) VALUES (4,'SECCION C',4,2,0,'1');

INSERT INTO MATRICULA (ID,ALUMNO_ID,CURSO_ID,SECCION_ID,TIPO_MATRICULA,FECHA_REGISTRO) VALUES (1,1,1,1,'1',SYSDATE)
COMMIT;
