
 ALTER TABLE SECCION
ADD CONSTRAINT FK_SECCION_CURSO_ID
FOREIGN KEY (CURSO_ID) REFERENCES CURSO (ID);


ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_ALUMNO_ID
FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO (ID);

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_CURSO_ID
FOREIGN KEY (CURSO_ID) REFERENCES CURSO (ID);

ALTER TABLE MATRICULA
ADD CONSTRAINT FK_MATRICULA_SECCION_ID
FOREIGN KEY (SECCION_ID) REFERENCES SECCION (ID);